accounts/urls.py
from django.conf.urls import url, patterns

from . import views


urlpatterns = patterns(
    "",
    url(r'^$', views.UserList.as_view(), name='list_user'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailUserView.as_view(), name='detail'),
    url(r'^getname/$', views.get_name, name='get_name'),
    url(r'^register/$', views.register, name='register'),
)

mysite/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

from django.conf import settings

urlpatterns = patterns(
    '',
    url(r'^', include('accounts.urls', namespace="accounts")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        '',
        (r'^media/(?P<path>.*)$',
            'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    job_title = models.CharField(max_length=100, default='Unemployed', null=True)
    region = models.CharField(max_length=100, default='', null=True)
    interest = models.CharField(max_length=100, default='', null=True)
    specialism = models.CharField(max_length=100, default='', null=True)
    avatar = models.ImageField(upload_to='user_avatar', null=True)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Account
from django.forms import ModelForm


class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)
    job_title = forms.CharField(max_length=50, required=True)
    region = forms.CharField(max_length=50, required=False)
    interest = forms.CharField(max_length=50, required=False)
    specialism = forms.CharField(max_length=50, required=False)
    avatar = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ('username',
                  'email',
                  'password1',
                  'password2',
                  'first_name',
                  'last_name',
                  'job_title',
                  'region',
                  'interest',
                  'specialism',
                  'avatar')

    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
            account = Account.objects.create(user=user)
            account.job_title = self.cleaned_data['job_title']
            account.region = self.cleaned_data['region']
            account.interest = self.cleaned_data['interest']
            account.specialism = self.cleaned_data['specialism']
            account.avatar = self.cleaned_data['avatar']
            account.save()

        return user

accounts/views.py
from django.shortcuts import render
from django.contrib import auth
from django.core.context_processors import csrf
from django.views import generic
from .models import Account
from mysite.views import FilteredListView
from django.conf import settings
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .forms import NameForm, MyRegistrationForm


def login(request):
    if request.method == "GET":
        c = {}
        c.update(csrf(request))
        next = request.GET.get('next', '')
        next = next[:-1]
        c.update({'next': next})
        return render(request, 'accounts/login.html', c)
    if request.method == "POST":
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")
        remember = request.POST.get("remember", "no")
        next = request.POST.get('next', '/')
        if (username == "" or password == ""):
            error_message = "Please type in both username and password."
            return render(
                request, 'accounts/login.html', {'error_message': error_message}
                )
        else:
            user = auth.authenticate(username=username, password=password)

            if user is not None:
                auth.login(request, user)
                if remember == "yes":
                    settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False
                else:
                    settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = True
                return HttpResponseRedirect(next)
            else:
                next = next[:-1]
                error_message = "Your loggin is invalid. Please try again."
                return render(
                    request, 'accounts/login.html',
                    {'error_message': error_message, 'next': next}
                    )


def logout(request):
    auth.logout(request)
    return render(request, 'accounts/logout.html')


class DetailUserView(generic.DetailView):
    template_name = 'accounts/detail.html'
    model = Account


class UserList(FilteredListView):
    template_name = 'accounts/member_directory.html'
    context_object_name = 'accounts'
    paginate_number = 4
    search_fields = [
        'user__first_name', 'user__last_name', 'region', 'interest', 'specialism'
    ]

    def get_queryset(self):
        accounts = Account.objects.all().order_by('user__first_name', 'user__last_name')
        self.queryset = accounts
        return super().get_queryset()


def get_name(request):
    # if this is a POST request, we need to process the form data,
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('accounts:login'))
    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'accounts/name.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = MyRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('accounts:list_user'))

    args = {}
    args.update(csrf(request))
    args['form'] = MyRegistrationForm()
    return render(request, 'accounts/register.html', args)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block title %}User Profile{% endblock title %}

{% block main_content %}
<div class="wrapper">
<h2>USER PROFILE</h2>
<div class="pull-left width-20">
	{% if account.avatar %}
		<img class="avatar-big" src="{{account.avatar.url}}">
	{% else %}
		<img class="avatar-big" src="{{ MEDIA_URL }}user_avatar\default_avatar.png">
	{% endif %}
</div>  
<div id="speechDiv" class="width-30">
<p class="speech">
<label>My name is </label>
{{account.user.first_name}} {{account.user.last_name}}
</p>
</div>
<div class="pull-left">
<p> Region: {{account.region}}</p>
<p> Interests:  {{account.interest}}</p>
<p> Specialism: {{account.specialism}}</p>
</div>
</div>
{% endblock main_content %}

accounts/templates/accounts/login.html
<h2>Login Page</h2>
{% if error_message %}
	<p>{{error_message}}</p>
{% endif %}
<form action = "{% url 'accounts:login' %}" method = "post">
{% csrf_token %}
<label for = "username">Username</label>
<input type = "text" id = "username" name = "username">
<br/>
<label for = "password">Password</label>
<input type = "password" id = "password" name = "password">
<br/>
<input type ="checkbox" name="remember" value="yes"/>
<span>Remember me</span>
<input type = "submit" value = "Login"/>
<input type = "hidden" name = "next" value = {{next}}/> 
</form>

accounts/templates/accounts/logout.html
<h2>Good bye!!!</h2>
<p>Click <a href="/">here</a> to go back to the homepage.</p>

accounts/templates/accounts/member_directory.html
{% extends 'base.html' %}

{% block title %}User List{% endblock title %}

{% block main_content %}
<div class ="wrapper">
<div class="hidden-overflow">
<h2 class="width-30 pull-left">Member directory</h2>
<div id="search" class="pull-right">
  <span>Search members</span>
  <div class="pull-right">
  <form method="get">
 		<input name="q" type="text" placeholder="Member name"/> 
   		<button type="submit">Go</button>
  </form>
  </div>
</div>
</div>
{% for account in accounts %}
<hr>
<div class="hidden-overflow">
	<div class="width-10 pull-left">
	{% if account.avatar %}
		<img class ="avatar-small" src="{{account.avatar.url}}">
	{% else %}
		<img class ="avatar-small" src="{{ MEDIA_URL }}user_avatar\default_avatar.png">
	{% endif %}
	</div>  
	<div id="nameAndJob" class="width-20 pull-left">
		<div id="fullName">
		{{account.user.first_name}} {{account.user.last_name}}
		</div>
		{{account.job_title}}
	</div>
	<div class="pull-right">
		<input id="viewButton" type="button" onclick="location.href='{{account.id}}';" value="View"/>
	</div>
</div>
{% endfor %}
</div>
{% if accounts.paginator.num_pages > 1 %}
<div class="pagination">
    <span>
        {% if accounts.has_previous %}
            <input class="step-buttons" type="button" onclick="location.href='?q={{ request.GET.q }}&amp;page={{ accounts.previous_page_number }}';" value="Previous"/>
        {% else %}
             <button class="step-buttons" type="button" disabled>Previous</button>
        {% endif %}
        {% for i in 'x'|ljust:accounts.paginator.num_pages %}
            <input class="step-buttons" type="button" onclick="location.href='?q={{ request.GET.q }}&amp;page={{ forloop.counter }}';" value="{{ forloop.counter }}"/>
        {% endfor %}
        {% if accounts.has_next %}
             <input class="step-buttons" type="button" onclick="location.href='?q={{ request.GET.q }}&amp;page={{ accounts.next_page_number }}';" value="Next"  />
        {% else %}
             <button class="step-buttons" type="button" disabled>Next</button>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock main_content %}

accounts/templates/accounts/name.html
<form action="{% url 'accounts:get_name' %}" method="post">
{% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" />
</form>

accounts/templates/accounts/register.html
<title>Register page</title>
<h2>Register Page</h2>
<form enctype="multipart/form-data" action = "{% url 'accounts:register' %}" method = "post">
{% csrf_token %}
    {{ form.as_p }}
    <input type ="submit" value="Register">
    
</form>